<?php include('header.php') ?>
<div class="content">

	<h2 class="fontface">The Book</h2>
	
	<ul id="left-nav">
		<li><a href="book.php">The Book</a></li>
		<li><a href="launch.php">Launch</a></li>
		<li><a class="on" href="reviews.php">Book Reviews</a></li>
		<li><a href="usbooktour.php">US Book Tour</a></li>
		<li><a href="wheretofindcwc.php">Where to find Crying with Cockroaches</a></li>
	</ul>
	
	<div id="main-content" class="one-col">
	<p align="justify"><strong>If only I could be so brave</strong> <br />
    Marianne Du Toit is the woman I wish I were brave enough to be. She is a marvel of gumption. Crying with Cockroaches tells the remarkable story of following her dream, persevering no matter how immense the struggle and the odds against her and her beloved horses. It's an enthralling adventure story, a heartbreakingly touching story of love for her horses and their courageous fortitude and Marianne Du Toit's personal journey to realize just who she is - her character and her power. Her journey is compelling in its enormity and her recounting of it is enthralling. But, also it is just a really fun read, a real page- turner. I loved it. Her ever so appealing personality came through loud and clear in her self-deprecating style. I understand how just about everyone she met on the way invited her into their lives, saying yes you can sleep on my floor, your horses can sleep in my yard and my dinner is your dinner and how about some grain for your four-legged friends. I fell in love with her immediately and rooted for her page after page. Her nutty dream of riding from Argentina to New York was so deliciously unbelievable. I was awestruck from the first page until the last.</p>
  <p align="right">P OSBORNE, usa</p>
  <p align="justify"><strong>A journey of mind, body and horse</strong><br />
    A simple tale, which explores the complexities of the human and equine spirit and indeed the marriage of the two. Both are pushed to the limits on this revealing epic journey, with very happy and very sad consequences. Courageous yet fragile, worried yet full of conviction, amongst people yet often lonely, carefree yet feeling unsafe are themes which form part of Du Toit's daily physical and psychological journey into the unknown. I found her easy open writing style allowed me re-live her journey for myself. This book, the woman, her horses and indeed many of the people she shared her life with, will remain an inspiration to me.  </p>
  <p align="right">D Kilmartin, eire</p>
  <p align="justify"><strong>An Enthralling Adventure by a Remarkable Woman</strong> <br />
    Marianne Du Toit tells the story of her great adventure - solo with two horses for 21 months from Argentina to New York - with eloquence and with a simplicity and honesty that is touching and heart-warming. It is just impossible not to fall under the spell of this charming, courageous and unassuming young woman, whose empathy with fellow beings and all living creatures shines through on every page. That her book universally evokes this feeling of affinity and rapport with the reader is borne out by the fact that every reviewer on Amazon in the US and UK describes it as inspirational. The author downplays the very real hardships and dangers that she faced, choosing to focus on the generosity of the local people and the sense of companionship with her two horses. Reading the book, which is beautifully produced with many colour photographs, turns into a life-affirming experience and bears testimony to the difference that one person can make in bringing about changes in the perception of many others. It challenges us to rediscover our humaneness in an age of confused values by showing what we are all capable of. The power of the book lies in bringing this message across without ever pretending to any higher mission, but simply by relating her adventures with compassion, optimism and humour. This is a book that will stay with you for a long time and make you rethink as to what life is all about. An extraordinary journey by a most remarkable woman - one of my all-time favourite books!</p>
  <p align="right">P DE VILLIERS, sa</p>
  <p align="justify"><strong>WOW!</strong> <br />
    Crying with Cockroaches blew me away. This book is a real page- turner, I couldn't hardly put it down. If you are a horse person (as I am) you will know what an undertaking this was and by a novice horse rider. Her courage and tenacity were overwhelming as she made her journey across several very poor countries where women are not always held in high esteem. The dangers she encountered along the trail, I honestly don't know how she got through it. She would go days without food but always taking the best care of her horses. She really is an inspiration to women and to horse people. You won't be sorry if you buy this book. It is a great read!</p>
  <p align="right"> T FOLKS, usa</p>
<p align="justify"><strong>Perseverance</strong><br />
  &quot;Crying With Cockroaches&quot; is a splendid example of perseverance. While many adventure stories leave two choices, continue or die, Marianne always had a third option, just simply quit. To be sure, when her journey became unbearable, she could have, quite easily, sold or given her horses to a deserving family, hopped on a flight and returned to the comforts of her home in Ireland. Quitting for her was never an option and through sheer determination and fortitude she accomplished her goal. What an inspiration for those battling an illness, job layoff, divorce, bankrupcy, loss of a loved one, etc., etc. Moose Tenny said, &quot;Winners never quit and quitters never win.&quot; Marianne is a winner and will inspire readers of her book to likewise become winners.</p>
<p align="right">J ELLINGTON, usa</p>
<p align="justify"><strong>Awesome</strong><br />
  Unique, intriguing, unbelievable, overwhelming, heartwarming, exciting, rewarding, and inspirational! Marianne Du Toit shares her adventure in a wonderfully written book that captivates your interest from the very beginning. A book very hard to put down once the reading begins! its not often that a book leaves you a better person when you are through reading it, but this book definitely does!! </p>
<p align="right">M MAGELUND, usa</p>
<p align="justify"><strong>I highly recommend this book!</strong><br />
  This book takes you through South and North America via the back route. <br />
  The author literally knocks on doors throughout her ride and it is fascinating to see how she and her horses are received in homes spanning the most humble abode to mansions of the rich. She starts out speaking almost no Spanish and does not have much riding experience nor does she really plan her journey ahead of time! She recounts her adventures with wit and charm and despite the hardships and dangers always looks on the bright side. In fact, I found her approach to life very inspiring and hope some of it will rub off on me after reading this! I couldn't put this book down and was sorry when I turned the last page.</p>
<p align="right">S MURCHISON, usa</p>
<p align="justify"><strong>Adventure, Intelligence, and Humor</strong><br />
The Prime Minister of Ireland, who introduces this book, eloquently endorses adventure as an integral component in each of our lives. A quote from Helen Keller states, &quot;Life is either a daring adventure or nothing at all.&quot; Marianne Du Toit was born in South Africa and raised on a farm, where she had limited time on horseback and spoke no Spanish. She knew from childhood that she would have a special adventure at some point. In 2002, she flew to Buenos Aires, purchased two horses and rode 6,000 miles from Argentina to New York City. Within the pages of her book, Crying with Cockroaches, Marianne pushes the envelope, riding into unknown territory with no safety net. She finishes her ride with a smile and a barrel full of memories. It's hard to comprehend the challenges, much less the rewards of putting life and limb on the line every single day for over 21 months. It' s uncanny that Marianne drank from streams or with the local people and had no illness except a half-day of &quot;runny tummy.&quot; Her descriptions of the majestic beauty of the terrain, the warmth and hospitality of those living in poverty, and her avoiding tragedy through wit, luck, and unfailing trust all combined to make this adventure spellbinding. When asked if she was scared on her journey, she replied that she tried to stuff fear into her saddlebag but there just wasn't room, so she had to rely on trust. Sportswriter Grantland Rice once wrote: </p>
<p align="justify">&quot;When the one great Scorer comes to write against your name, He writes not that you won or lost, but how you played the game.&quot; </p>
<p align="justify">In this book, Marianne plays the game in excellence, inspiring and enthralling her readers, just like those on the journey. She is truly a remarkable woman, a superb storyteller, and the ultimate adventurer.</p>
<p align="right">S ROBERTS, usa</p>
<p align="justify"><strong>Courage and inspiration...</strong><br />
  I had the opportunity to get to know Marianne when her 2 &quot;American&quot; horses stayed with me on her journey. But it wasn't until I read her book that I truly grasped what an amazing feat this quiet, unassuming young woman had accomplished! In her book she takes us with her through some of the most grueling territory on the planet. We meet the rich and poor who enriched her life (and ours) by sharing their own stories and often meager existences. Animal lovers will understand her love for her horses and concern for the lack of care and sometimes inhuman treatment for horses, dogs, etc that she encountered on her journey. Marianne's courage and perseverance is an inspiration to us all. I would highly recommend this book to older children and young adults, too.</p>
<p align="right">P DAVIS, usa</p>
<p align="justify"><strong>An Extraordinary Adventure</strong><br />
Marianne Du Toit gives &quot;one day at a time&quot; a whole new feel as she relates her fascinating adventure with an ease that leaves the reader feeling that they have stowed away in her (occasionally troublesome) saddlebags. Du Toit's writing achieves that difficult task of using animals as main characters without anthromorphizing them. I grew attached to the horses as her true compatriots, yet Du Toit never forgets that horses and humans are not the same. They are a team, albeit of the &quot;odd couple&quot; variety. Although I am a city dweller, I laughed with, cried at, thrilled in, and felt deeply connected to the adventures of this young adventurer and her equine travel partners as they struggled to make their way. </p>
<p align="justify">Each evening, I eagerly looked forward to resuming the journey as the people, the roads, the fields, the homes and the crumbling out buildings that made up Ms. Du Toit's daily experience were introduced and explored. Her journey was of the spirit and the body. At times, the &quot;beasts of burden&quot; she encountered were not equine, but the overall brilliance of human beings shines through, thanks to her intimate, honest writing. Marianne Du Toit's spirit is a gift and her story a must-read.</p>
<p align="right">M SHERMAN, usa</p>
<p align="justify"><strong>Better her than me!</strong><br />
When you meet Marianne Du Toit she doesn't look crazy. She seems like a perfectly normal, charming and intelligent young woman. And then she starts telling you stories about her trip, and you start to wonder... </p>
<p align="justify">Then you read her compelling narrative and you have to wonder how this woman summoned the courage to take on such an incredible journey. She claims she had no idea how tough it would be and that seems as good an explanation as any. Thankfully, nobody suggested she climb Mt. Everest on roller skates. </p>
<p align="justify">Her book is a wonderful tale of what the human spirit can accomplish with a healthy dose of determination and a little grass roots help along the way. Du Toit uses her equine adventure to enthrall and enlighten.</p>
<p align="right">G PETTY, usa</p>
<p align="justify"><strong>An arduous journey that you won't want to end</strong><br />
  What struck me most about this book was the sheer fortitude, ingenuity, perseverance and luck that Marianne evoked. Her initial lack of knowledge about horses makes it even more remarkable that she completed the journey at all, much less with such grace and aplomb. The way she tackles her dream trip is an inspiration indeed. A unique read that is sure to keep you turning the pages and leave you wanting to hear more. What will she do next?</p>
<p align="right">P BROWN, usa</p>
<p align="justify"><strong>Top Read</strong><br />
  &quot;Crying with Cockroaches&quot; is a fine read written with dexterous clarity by someone who does not know the meaning of the word &quot;Can't&quot; . Enjoy.</p>
<p align="right">T WHELAN, eire</p>
<p align="justify"><strong align="justify">What a Treat</strong><br />
What an adventure shared with this lovely young lady! All I can do is shake my head in wonder as I read her vivid account of a mind made up coupled with a willingness to trust her instincts and abilities daily in a completely foreign environment. I thoroughly enjoyed the immersion into an adventure that I escape to often as I go through my daily routine. <br />
Thank you Marianne.</p>
<p align="right">J JOHNSON, usa</p>
<p align="justify"><strong>A long rider's dream trip</strong><br />
  This is an excellent account of a long ride on horseback. Marianne was following her dream and sort of was trying to capture the feelings that Aimé Tschiffely must have had when he made this ride in 1926. We're not talking a ride in the park, but a really long ride from Buenos Aires, Argentina to New York City, USA! What an adventure by a courageous, young gal who never knew where she would lay her head night after night. What fun she had. She is quite honest about her feelings, things she had to learn and about caring so much about her horses. There are dangers, tears, loss, laughter and accomplishment in this book. A great read! 21 months on the trail will keep you glued to the pages of this very nice account complete with fabulous color pictures of lots of places. Thank you Marianne for sharing your adventure with us. </p>
<p align="right">R ROLLINS, usa</p>
<p align="justify"><strong>Amazing journey</strong> <br />
  Being a fiction fanatic, I was in 2 minds whether to buy this book, but something kept drawing me to it and eventually I gave in, how glad am I!! I would recommend this book [and have!!] to everyone, even those with limited knowledge of horses [I myself have never even sat on one!!] </p>
<p align="justify">
  I loved everything about the book, the size of it [slightly bigger than normal trade paperback], the cover, the high quality paper, the pictures throughout and especially the story. </p>
<p align="justify">
  It’s truly amazing what this girl put herself through to follow her dream and I found myself thoroughly engrossed throughout.
  </p>
<p>Buy this book today you won't be disappointed!!!!<strong></strong></p>
<p align="right">J CONNOR, N Ireland</p>
<p align="justify"><strong>Crying with Cockroaches - a great find</strong><br />
  &quot;Crying with Cockroaches&quot; provides an interesting insight into an extraordinary journey of both personal and geographical achievements. Du Toit documents her trek with two horses in an honestly written account. The beautiful pictures help bring the story and the terrain of the Americas to life. Animal welfare is a predominant point and seems even more relevant as the relationship and co-dependency between Du Toit and her two Criollos develops. The story also uncovers the good and bad of human behaviour in a trip so unpredictable and dependent on the offerings of others. The most appealing aspect of this book however is in my opinion, the determination and perseverance of the writer who was focused in the pursuit of her dream. This is inspirational in view to the challenges she faced in a seemingly impossible journey. These messages will no doubt, be encouraging and motivational to any reader of this book. A highly recommended read to any adventure seeker or those in face of a challenge!</p>
<p align="right">S DURKIN, eire</p>
<p align="justify"><strong>An unexpected page-turner</strong><br />
A friend suggested I get this book and I was skeptical at first as I have read only a very few, true-adventure stories that excited me. Crying with Cockroaches however had me mesmerized from the very start. I purchased the book in January and have read it cover to cover, twice already. </p>
<p align="justify">The voice of the author is so clear and her honesty, humour and optimism transparent on every page. All I can say is get this book. It is an easy read, well-written, great photographs and an excellent example of what we all can accomplish with determination and a strong will. The author is truly likeable and also humble, despite having undertaken this magnificent journey on her own but for two equine companions. She did not even know much about riding but her love for horses and really all animals and her perseverance to make this happen, made her triumph at the end. You'll laugh and cry, be exhilarated and moved as you are swept through the Americas on this epic adventure. </p>
<p>It's not a &quot;horsey book&quot; but just really a five-star read to be enjoyed by all ages. </p>
<p>HIGHLY RECCOMMENDED.</p>
<p align="right">GORDON M, canada</p>
<p align="justify"><strong>A page-turner written with honesty and humour</strong> <br />
Crying with Cockroaches is a delightful, frank and thoroughly engaging account of the author's first-hand experience of travels through the Americas over two years with just two horses for company. </p>
<p align="justify">In this fascinating read Du Toit tells it as it is, sparing no details. With her skillfully simple style, the reader is drawn in, sharing Du Toit's epic journey through tears, frustration, exhilaration and joy. </p>
<p align="justify">Not just beautifully written but also beautifully illustrated throughout with more than 100 colour photos that complete the story, this is a must-read.</p>
<p align="right">G BROOKS, uk</p>
<p align="justify"><strong>What a book</strong><br />
  Totally amazing!! A young lady with heart and determination decides to go on a journey and does it! She shared her ups and downs and often made a person feel like you were traveling right along with her! It was wonderful to know that even within the most remote parts of her journey the true essence of mankind still showed through, kindness, generosity, caring, thoughtfulness, consideration all done with sincerity, a true giving. Not many could do such a journey, and what a pleasure it was to read the book, once started it was hard to put it down because there was an anxious curiosity about what was going to happen next! With quiet confidence she rode and what a blessing it is to have her share her wonderful journey in this book!</p>
<p align="right">M MAGELUND, usa</p>
<p align="justify"><strong>The highs and lows of an adventure of a lifetime</strong><br />
  Any horse owner, rider, animal lover and those interested in travel will love this book. Told in a straightforward way it makes you feel as though you are with her experiencing the fear, frustrations, sadness and joy, the dogged determination that keeps her and her two faithful friends, Mise and Tusa (Me and You in Irish) going. A truly compelling read.</p>
<p align="right">J DUNLOP, n ireland</p>
<p align="justify"><strong>We can make our dreams come true</strong> <br />
  An extraordinary tale of an extraordinary voyage by an extraordinary woman. An honest, moving, practical account of life on the road with two horses covering thousands of miles. A hopeful, witty, positive outlook irrespective of the situation is what saw this determined woman through to make her dream a reality. The reader shares the adventure with Marianne through her simple storytelling style gaining many insights into how Marianne kept herself going and also into the lives of the people and the creatures Marianne met along her way. </p>
<p align="justify">
  Marianne's optimistic approach whatever the obstacle is an inspiration for every reader. &quot;Glass half full not half empty&quot;, as she says herself!</p>
<p align="right">O TUNNY, eire</p>
<p align="justify"><strong>Instead of &quot;if only&quot;: She did</strong><br />
How well you get to know someone when a reading a book about someone you thought you knew somewhat! Almost like a 2-year biography, because you get to know Marianne Du Toit through her emotions, character, thoughts and actions. And you get to know her companions, which happen to be horses. My reactions throughout have been mostly that of amazement and admiration. Why don't we all do what we really want to do - break free from conformity and follow our pursuits and interests - especially when it involves animals, new countries, a journey, planning, self-exploration, new experiences daily, a great cause - the ripple-effect of which will be effected for many years to come. This is a book for young, old, fiction-readers, non-fiction readers, male, female, of any nationality and all my friends will be receiving a copy for their birthday this year.</p>
<p align="right">C DE KOCK, usa</p>
<p align="justify"><strong>A journey of two continents begins with just one step</strong> <br />
  Marianne Du Toit's first book is a singularly extraordinary achievement. Engaging, heartwarming and universally relevant, her easy writing style belies a truly global lesson for all - it is very often those who we perceive to have the least in life who have a generosity of sprit beyond our comprehension. Marianne’s strength of character and determination to make a difference to the lives of those less fortunate - both humans and animals - makes for a true page turner, and her easy writing style carries the reader along this extraordinary journey as if it were a quiet amble down a country lane. The breadth and depth of her achievement goes beyond the continents she traversed on horseback and this book will live on in the hearts and minds of all of those fortunate enough to read it.</p>
<p align="right">N HORGAN, eire</p>
<p align="justify"><strong>Inspirational</strong> <br />
  What a great read! Marianne Du Toit's determination proves that nothing is insurmountable if you put your mind to it and this book motivated me to achieve my own personal goals. I couldn't wait to find out what lay around the next bend on the long and lonely road she traveled and I found myself laughing and crying along with her. In general, my faith in human kindness and generosity was reinforced by most of the people she met along the way. Crying with Cockroaches is a truly inspirational book by a truly inspirational woman.</p>
<p align="right">J CONROY, eire</p>
<p align="justify"><strong>A sophisticated yet easy read</strong><br />
  While reading &quot;Crying with Cockroaches&quot;, I felt I was riding right along on the whole journey with Marianne. Marianne Du Toit wrote in a sophisticated, yet easy manner. For those who have never traveled outside the more developed countries, her book gives an in-depth view of the daily life of how much of the world lives. Not only is Crying with Cockroaches an entertaining and educational book to read, I hope the author's passion for animal rights will have a positive effect on readers and hopefully make the world a better a place for them. Be prepared to shed a few tears also!</p>
<p align="right">D JOHNSON, usa</p>
<p align="justify"><strong>An inspiration to follow your dreams</strong><br />
  Told simply and honestly, this is a truly amazing adventure undertaken by a very courageous woman. Marianne was determined not to allow fear stop her from following her dreams, a lesson that we could all apply to our own lives. This story is testament to the basic goodness and generosity of most people, since much of the time she relied on strangers for accommodation, food and stabling her of her beloved horses as she trekked from South America to New York. Her journey inspired many people along the way. Her photos, which are nicely placed throughout the book provide a visual link to her journey and help to draw you in. I felt I was traveling the journey with her as I read and it was with some sadness and a tear in my eye that I finished the book! Enjoy!</p>
<p align="right">P McGINTY, eire</p>
<p align="justify"><strong>A great read!</strong><br />
  Gripping stuff from an amazing woman who did an extraordinary journey with her two equestrian companions. The book contains beautiful pictures, which makes traveling 'with' Marianne realistic and enjoyable. The tales of her adventures, disappointments and experiences of human kindness makes the book 'unputdownable'. </p>
<p align="justify">
  A must read for those who enjoy reading travel writings!</p>
<p align="right">M KLOPPER, uk</p>
<p align="justify"><strong>This is an excellent book</strong><br />
A totally honest account of one woman's struggle to travel alone from South America to New York on horseback. What is refreshing about this book is that it is devoid of jargon or spin - it is as if your best friend is talking to you at the end of her day to fill you in on all that has happened. Marianne's account of her journey is vivid and alive you can almost taste the dust and smell the hay. </p>
<p align="justify">A woman traveling alone and depending on strangers for food and shelter through so many countries must be a recipe for disaster, however one woman has done what many of us would feel was impossible. From this book we learn that if we are positive and truly believe in what we are doing we can achieve almost anything..... An excellent read.</p>
<p align="right">C ROCHE, eire</p>
<p align="justify"><strong>Even better the second time around</strong> <br />
  Crying with Cockroaches is one of those books that gets you hooked, easily, disarmingly and without trying to hard. The author, Du Toit, has a unique writing style. Also she does not seem to take herself too seriously yet she feels passionate and is serious about animal welfare, love for her horses and the environment. I enjoyed this book from start to finish. It's exciting, has excellent pace and will most definitely warm your heart. It also gave me itchy feet to want to get out there and do things...I'm reading Cockroaches for the second time and enjoying it even more (if that was possible!).</p>
<p align="right">J LEWIS, uk</p>
<p align="justify"><strong>Cry with cockroaches</strong><br />
  I found myself filled with admiration at sheer scale of her journey. This is truly traveling the hard way, across altiplano and river, through jungle and over mountain. Marianne's travels, force her to confront the limits of both body and spirit. She experiences the unexpected generosity of people and agonising disappointment, which are invariably part of such an ambitious adventure. <br />
  Few of us will venture as deeply into the unknown as Marianne Du Toit or Tschiffely, but her book does highlight the enormous possibility, which is dormant within each individual. A remarkable account of an incredible journey.</p>
<p align="right"> G MEEHAN, eire</p>
<p align="justify"><strong>I loved this book</strong><br />
  This book takes you through South and North America via the back route. The author literally knocks on doors throughout her ride and it is fascinating to see how she and her horses are received in homes spanning the most humble abode to mansions of the rich. She starts out speaking almost no Spanish and does not have much riding experience nor does she really plan her journey ahead of time! She recounts her adventures with wit and charm and despite the hardships and dangers always looks on the bright side. In fact, I found her approach to life very inspiring and hope some of it will rub off on me after reading this! I couldn't put this book down and was sorry when I turned the last page.</p>
<p align="right">C MACTAGGART, uk</p>
	
	</div>

</div>

</div>
<?php include('footer.php') ?>