<?php include('header.php') ?>
<div class="content">

	<h2 class="fontface">The Book</h2>
	
	<ul id="left-nav">
		<li><a href="book.php">The Book</a></li>
		<li><a href="launch.php">Launch</a></li>
		<li><a href="reviews.php">Book Reviews</a></li>
		<li><a class="on" href="usbooktour.php">US Book Tour</a></li>
		<li><a href="wheretofindcwc.php">Where to find Crying with Cockroaches</a></li>
	</ul>
	
	<div id="main-content" class="one-col">
	<p>End of September 2007 I flew to Atlanta Georgia to begin a two-month book tour through the United States.</p>
  <p>A lot of work and energy had gone in to the planning of this trip, not only trying to create interest for TATA again, but also re-establishing contact with people in the different states, working out the logistics for when I was going to be where, organising presentations and publicity.</p>
  <p>In hindsight I probably should have spent more time on contacting media outlets rather than trying to re-connect with everyone who assisted me three years earlier as this would have resulted in more exposure for my book. However, my tour was not just about book sales and I was adamant to give a signed copy of my book to each and every person who had so generously helped me and the horses as we traveled up the east coast of America. It was just a small way of saying ‘thank you’ and I was proud that I managed to give a copy of Crying with Cockroaches to almost everyone apart from seven or eight people I could not get hold off.</p>
  <p>I was hoping that all those individuals who had helped me during the US stretch of my trip would be as enthusiastic to be of assistance again. I needed however to remain realistic that I might get different levels of reception and hospitality and that not everyone would be as happy as in 2003/2004 to see me again.</p>
  <p>What I found interesting during the US book tour was how with some people it was as if no time had passed since we were last together and everything was still as easy and uncomplicated as before and with others, the dynamics had changed. Now that I appeared just by myself, no horses but instead a van full of books, all of a sudden with some there was simply no common ground anymore with very little to share. But that was fine too. I had no high expectations so I was not overly disappointed at the changed interactions in some instances. More importantly the book tour also gave me the opportunity to meet some new, very interesting people who embraced my story and book with real passion and sincerity. </p>
  <p>Marilyn had her work cut out in the weeks prior to my arrival and was very busy lining up book signings, interviews and a place to store my books. She also liaised numerous times with the people at Savannah Port to ensure that the 7000 copies of my book arrived safe and sound from Spain where they were printed by GraphyCems. There was a fair bit of red tape and organising but Marilyn as usual just took it in her stride and I knew I could call on her whenever I needed something.<br />
    <a href="http://www.graficascems.com" target="_blank" class="pagetext">www.graficascems.com</a></p>
  <p>Todd, generous owner of Camanchi, the Appaloosa I used for the US stretch of my journey, picked me up at the airport. He was exactly the way I remembered him - warm, chatty, enthusiastic and funny – and the few hours drive from Atlanta to Albany passed too quickly.</p>
  <p>Diane and Joel received me with the same hospitality they did three and half years earlier when I arrived on their doorstep with two horses at my side. The same was the case when I met with Marilyn again the following day. It was good to see old friends again.</p>
  <p>Diane helped me in numerous ways, including designing the “ABC Person of the Week” stickers that would go on my book, posters and also an advertisement that would be used by INGRAM. I had free access to her computer and she and Joel allowed me to use their home as if it was my own. Evening times were sociable with good food and wine.<br />
    <a href="http://www.studiodj.net" target="_blank" class="pagetext">www.studiodj.net</a></p>
  <p>On my second night, Diane had invited a group of people over for dinner. Among them was a fascinating woman called Jane Wilson who runs Sunnyland Farms, a pecan enterprise that she and her (now deceased) husband started in 1948. Within a short time of meeting Jane she announced that I would be storing my books at her company, which was only a few miles up the road, free of charge. Not only that, but she would also organise her staff to put the ABC stickers on each and every one of the 7000 books – a job that would have taken Marilyn and I probably three days to finish.</p>
  <p>We were also invited by Mrs. Wilson to attend the unveiling of ‘Boy with Coat” – a painting by Arthur R Berry who has had an accomplished career and involvement in the Arts since 1967. A splendid dinner followed at Mrs. Wilson’s tastefully decorated home, filled with many original works of art.<br />
    <a href="http://www.uga.edu/cits/documents/WillsonGAMagazine.pdf" target="_blank" class="pagetext">http://www.uga.edu/cits/documents/WillsonGAMagazine.pdf </a><br />
    <a href="http://www.sunnylandfarms.com" target="_blank" class="pagetext">www.sunnylandfarms.com</a></p>
  <p>Three days after my arrival in Georgia, Marilyn organised a rented truck and Todd and Bobby took a day off to travel all the way to Savannah on the east coast to pick up my books.</p>
  <p>Over the next few days I did an interview with Ruthie Garner on WALB TV and had a book signing at The Bookstore in Camilla. Great was my surprise to see Camanchi in front of The Bookstore brought there by Todd and I struggled to hold back the tears, hoping that he remembered me too. He looked even more like a wise old man and I thought had acquired more spots.</p>
  <p>I also spoke at a local school and did another signing over two days at the Albany Classic Charity Horse Show. </p>
  <p>I was looking forward to seeing the Tooles again in Colquitt Georgia where Terry had everything in place for me to do a signing at the Bride and Gift Gallery, owned by his daughter Tammy. He also made sure to have had two notifications printed in the Miller County Liberal (which he owns), prior to my arrival. That evening we were entertained in the Cotton Hall Theater to a production of Swamp Gravy, a play that has garnered numerous awards and much recognition, including being name a Cultural Olympiad Event in 1996.<br />
    <a href="http://www.millercountyliberal.com" target="_blank" class="pagetext">www.millercountyliberal.com</a></p>
  <p>Leaving Albany GA after twelve much enjoyed days, I traveled north to meet with Justin for lunch in Dublin GA, popped in to see the Yoder Mennonite family, spent a short while with the Holland Family in Wrightsville and stayed two nights with Tommy and Barbara in Wrens.</p>
  <p>In South Carolina I was warmly received by Irma, with whom I stayed for three nights. She managed to arrange an informal signing at a cabin-rent facility she owns and also interest from a newspaper in Saluda when I presented the local library with a copy of my book.</p>
  <p>During this time I took a one-day trip to Columbia where I was going to do a book signing. I have been in touch with the manager of the Happy Bookseller since three months previously and had also sent them posters to put up, announcing the event. The day was an anticlimax to say the least. Not only was there not a poster in sight when I arrived, but also nobody knew I was there. Of the four people that came in to see me, three of them were ‘sent’ by somebody in North Carolina whom I told about the signing and the fourth person was Lou Ann whom I knew from 2004. </p>
  <p>In South and North Carolina I also had brief meet-ups with Douglas Morris, Mark and Karen Thompson, Dalfred Wilson, Levane Rape, Glen and Deena, Lee Ann Helms, Mark, Gina and Boyce. Everyone was very appreciative to have received copies of the book.</p>
  <p>Surry was introduced to me through Jonathan Friedlander (more about him later) and ended up becoming not only a fantastic help and support but also a very good friend. He has to be one of the most interesting people I have ever met with an enthusiasm and lust for life and with a sense and appreciation for adventure that is unparalleled. Not even mentioning his no-agenda generosity. To read more about Surry go to “PEOPLE” under the MDT section of www.mariannedutoit.com</p>
  <p>Surry organized numerous things while I was staying with him in Raleigh. One day alone I had a television interview, two radio interviews and a presentation and signing at the American Institute of Health and Fitness with about 60 people attending. Dinner before the presentation at the Health Institute with Surry and his special nun friends Echo and Teresa was a humorous and serene affair.</p>
  <p>More action followed the next few days with presentations and signings at McNair Country Acres, the Chapel Hill Institute for Cultural and Language Education, the Rotary Club and finally the Equine Club Veterinary Department of the university.</p>
  <p>I was fortunate during my stay in Raleigh also to have become acquainted with Joe, a friend of Surry who was just a great guy and full of ideas. Not forgetting the numerous young women from the nearby university who were of great assistance to Surry (and were to me too), helping him with all his different projects on a daily basis given that he is blind.<br />
    <a href="http://www.sugarhollowretreat.com" target="_blank" class="pagetext">www.sugarhollowretreat.com</a></p>
  <p>During my stay with Surry I met a young man called Adam Sheppard who was on a ‘book mission’ himself. A highly motivated recent graduate who worked every hour of the day to support himself and also to promote his book; he ultimately had very good success when HarperCollins became his publishers.<br />
    www.scratchbeginnings.com

</p>
  <p>My stay with the Cart family near Powhatan, Virginia, as comfortable as when I visited with the horses, included a signing at the library in town as well as attending the Powhatan Grape Festival with Friends of the Library.

</p>
  <p>Middleburg was a pleasant visit this time around. With nobody causing negative vibes I actually got to relish the charm of this beautiful little town and had a fantastic time with Peter and Barbara who showed me endless hospitality. 

</p>
  <p>Patty’s place was another ‘safe haven’ and with no extra bed available, she had no qualms sleeping on the downstairs couch for a number of nights so that I could have the comfort and privacy of her bedroom.

</p>
  <p>A signing at the Galloping Grape, an equestrian/wine shop in Warrenton was interesting and laid back. I was looking forward to seeing Glenn and Amy again and in particular the two siblings they had adopted from Russia. To read more about their story, go to this link:<br />
    <a href="http://www.northernvirginiamag.com/family/2008/12/17/adoption/" target="_blank" class="pagetext">http://www.northernvirginiamag.com/family/2008/12/17/adoption/</a></p>
  <p>The evening brought a big surprise when a couple came in to the shop and introduced themselves as the new owners of Toto (whom they had bought from Alyse in Maryland). They had only read that morning about the signing in a local newspaper and were keen to meet me, given that Toto had been part of TATA. They agreed that I could come out to their place to see him. A beautiful farm surrounded by autumn trees and lots of space for the horses to roam outside, it was a perfect spot and even though seeing Toto again made me feel sad, I left with a peaceful heart, knowing that he had found an excellent home. He seemed happy with his other equine friends and it was obvious that his new owners doted on him.</p>
  <p>Unfortunately a signing in Washington that Alyse tried to organize with the Argentina Consulate did not materialize so instead I ended up spending two lovely days with Mary and Dante doing absolutely nothing but resting, eating and chatting. I also saw Alyse who lived opposite the Red Eagle Ranch and Jo who at that stage were not in good health. Though fragile looking, I could still see that sparkle in his eye. Sadly he passed away not long after. Click on the link below to read more about Jo Muldoon’s life.<br />
    <a href="http://www.washingtonpost.com/wp-dyn/content/article/2008/03/22/AR2008032202337.html#" target="_blank" class="pagetext">http://www.washingtonpost.com/wp-dyn/content/article/2008/03/22/AR2008032202337.html#</a><br />
    <br />
    <a href="http://www.briarleyhillretreat.com/" target="_blank" class="pagetext">http://www.briarleyhillretreat.com/</a></p>
  <p>An enjoyable evening was spent at the lovely home of Mrs. Ellie Shapiro with her new husband and pets she adores. She had the same vibrant demeanour that belied her seventy years and looked ten years younger than the last time I saw her.</p>
  <p>I made a new friend in Unionville Pennsylvania when Lizzy (owner of the Beresford Art Gallery) invited me to her home. She is an interesting, easy-going character and made me laugh throughout my stay. A signing was arranged and not only were copies of my book sold but also some of the exquisite art she exhibits in her house. <br />
    <a href="http://www.beresfordgallery.com" target="_blank" class="pagetext">www.beresfordgallery.com</a></p>
  <p>Ohio was next on the schedule, primarily due to the fact that Joy lived there and I thought it would be a terrible shame if I did not see her during the US tour. It meant going a little bit ‘off the beaten track’ but it was certainly worth the effort. Staying in one of her and her husband Don’s cabins was a real treat especially the jacuzzi on the deck overlooking stunning woods.<br />
    <a href="http://www.watersongwoods.com" target="_blank" class="pagetext">www.watersongwoods.com </a></p>
  <p>Joy is a real ‘go getter’ and with her natural charm and ease she had arranged a signing at Little Professor bookstore in Athens, a television interview with a university station and three presentations at different venues over a two-day period. I also got the chance to meet Robert Hunker in whose apartment I stayed in New York City when TATA had come to an end. Not only was he a most hospitable host while I was in Ohio, he also generously gave me the use of his ‘Greenwich pad’ for a second time during the book tour. Robert Hunker sadly passed away 24 March 2009 but leaves a legacy that would be difficult to ignore for many more generations to come.<br />
    Read this article to learn more about Robert’s life:<br />
    <a href="http://www.ohio.com/news/break_news/41751237.html" target="_blank" class="pagetext">http://www.ohio.com/news/break_news/41751237.html</a></p>
  <p>With a brief overnight at Thorncroft Therapeutic Riding centre in Pennsylvania and treated to a lovely dinner by Sallie and Sauders, I then stayed with Jim and Tiffany who in 2004 helped a great deal to ensure Mise had the best possible care before she was flown to Ireland. I was treated to lovely meals and got the chance to meet some of their friends.</p>
  <p>In New York City I was fortunate to be shown around the Explorers Club by a very helpful and energetic John who was a friend of Surry. I also attended a presentation there from another adventurer and in the process met many like-minded individuals. Through John I had a live interview with Dr Bob at BronxNet and I only have good things to say about him and the rest of the team at this station where good energy and attitudes ruled.</p>
  <p>Jonathan and Stacy run a successful therapeutic riding centre in Rochester New York and having met them before in Ireland, I was determined to see them before returning home. <br />
    <a href="http://www.equicenterny.org" target="_blank" class="pagetext">www.equicenterny.org</a></p>
  <p>I was glad I did, not only because they are great company but also because it was such a pleasure to have met Stacy’s parents (Pat and Barry) with whom I stayed for two nights and who truly are just magnificent people. It snowed a lot while I was there and I still have a vivid picture in my mind looking out of the windows of their cozy, wooden house with views of a partially frozen pond, ducks and Barry’s veterinary practice in the distance.</p>
  <p>Jonathan had a number of things lined up for me, amongst them an interview with ABC Channel 13, presentations and signings at the Harley School Theatre and George Eastman House as well as a signing at Borders bookstore.</p>
  <p>I flew back to Ireland on the 2nd of December after a long delay at the airport because of flight cancellations due to stormy weather. </p>
  <p>HEARTFELT THANKS TO EVERYONE WHO PARTICIPATED AND HELPED AND ASSISTED IN MAKING THE US BOOK TOUR MOST MEMORABLE.<br />
  </p>
	
	</div>

</div>
<?php include('footer.php') ?>